language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: y46/6F5Kqvm9iZwazzb54/urbtZHgKkmZs1Lj+BmbGSbr6PfJdRWiEh5kTskPzi1nbPFaCt3ddKDpcFfHzufzSt3sCarmbdTAjOJ4Se2u2IDYBvIt7ksMRB5VyCXnAd6POn2DAVkaQjEeUFySWDJl8PQgAeW6lj548WE7OeqJihfCZzPxh/txnkGIQYTTiai3b2pWm7zFFQ9jwpXASU71mlmtd0VuRKYQUUDSPSgJLSFTWshS3I9dKK7lLCYAWXkJCeijpLB880ffXTtDNJB286daO6Rtonxwl/1J8U2z2OGE3vVadsnlvhUEgCVGOS1VPOk443zuOrcuSyAt0j7s78eCsPY79nU8ve41QHZOJnH3O7XTt+jr1OjUnzrlF7K9dDzVnII5atmdrqej4c4LKr9lcZONSxnjWU0TbHr9MW1lokwOOSZcYkzkQB1MFeb96Oe4SbeKDGl8yjYA2kYVQA6cXqvnrVURdNGL0Eq+yjfSZFhfcNOwG0KBPVa7/zu+N7nbP2a/sAHuLkH/FgIwFS/UTf9FH6kz+WNJFRDZlDzlDxWdMmmjFyqt5O2NFLvVwUktx6RWLolxnlLxu7mDtrCzbM5n/QIUG0f+JiIWEyFd7/BqbfY9yp+iPiNgvj0uhvOWtHPR+LV58gW1O7Z/dpBsOkny2WVBcafYBd3q4k=
  app: viewing-party-2008-jas
  run: rails db:migrate
